name: Build and deploy web application

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: dist/
      - uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: maxgfeller.com
          username: trashcal@maxgfeller.com
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
